///
/// This file does the job of the linker -- it combines
/// various sources (including compiled scl) into one program.
///

rjmp _start                             // jump to entry

.include "asm/init.s"                   // _start itself
.include "asm/printer.s"                // print_number, etc
.include "asm/ivm.s"                    // ivm intrinsics
.include "asm/irq.s"                    // interrupts
.include "asm/font/font.s"              // generated font data
.include "asm/font/renderer.s"          // crt_cmd & crt_char
.include "asm/sanitize.s"               // bad thing handlers

// Generated by ict's DebugPrint operation
.const __ict.debugPrintInt  print_number
.const __ict.debugPrintChar print_char

.include "program.s"                    // generated asm file

