///
/// ivm.s -- Function for low-level interactions with ivm from scl
///

///
/// Halt machine untill interrupt
/// In: none
/// Out: none
///
.func
ivm_hlt:
    hlt
    ret

///
/// Get current stack frame
/// In: none
/// Out: [ptr]
///
.func
ivm_sf:
    gsf
    swap
    ret

///
/// Get current stack pointer
/// In: none
/// Out: [ptr]
///
.func
ivm_sp:
    gsp
    swap
    ret

///
/// Dynamically allocate memory on stack
/// In: [num bytes]
/// Out: [pointer]
///
.func
alloca:
    swap // move arg up
    push 0
    swap
    sub // invert
    sadd
    gsp
    swap
    ret

.func
ivm_bss_end:    
    push _ict_bss_end // generated by compiler
    swap
    ret

///
/// Shutdown VM
///
.func
quit:
    cli
    hlt
