# Generated by deepseek, with fixes by me

from svgpathtools import parse_path
from xml.etree import ElementTree as ET

IMAGE = 'Chars.svg'
OUTPUT = 'font.s'


def parse_font_svg(svg_file):
    tree = ET.parse(svg_file)
    root = tree.getroot()
    ns = {'svg': 'http://www.w3.org/2000/svg'}
    
    characters = {}
    
    for path_elem in root.findall('.//svg:path', ns):
        d = path_elem.get('d')
        if not d:
            continue
        
        path = parse_path(d)
        if len(path) == 0:
            continue
        
        start_x = int(round(path[0].start.real))
        start_y = int(round(path[0].start.imag))
        
        cell_col = start_x // 18
        cell_row = start_y // 18
        ascii_code = cell_row * 16 + cell_col
        
        commands = []
        for segment in path:
            seg_start_x = int(round(segment.start.real))
            seg_start_y = int(round(segment.start.imag))
            seg_end_x = int(round(segment.end.real))
            seg_end_y = int(round(segment.end.imag))
            
            xss = (seg_start_x % 18) - 1
            yss = (seg_start_y % 18) - 1
            if not commands or commands[-1][1:] != (xss, yss):
                commands.append(('moveto', xss, yss))
            
            xse = (seg_end_x % 18) - 1
            yse = (seg_end_y % 18) - 1
            commands.append(('lineto', xse, yse))
        
        if ascii_code not in characters:
            characters[ascii_code] = []
        characters[ascii_code].extend(commands)
    
    return characters

def encode_command(cmd, x, y):
    if cmd == 'moveto':
        type_byte = 0x01
    elif cmd == 'lineto':
        type_byte = 0x02
    else:
        type_byte = 0x00
    
    coord_byte = ((x & 0xF) << 4) | (y & 0xF)
    return (type_byte << 8) | coord_byte

def generate_assembly(svg_file, output_file):
    characters = parse_font_svg(svg_file)
    
    pointer_table_size = 256 * 8
    
    char_data = {}
    for i in range(256):
        if i in characters and characters[i]:
            char_data[i] = characters[i]
        else:
            char_data[i] = []
    
    current_offset = pointer_table_size
    offsets = {}
    for i in range(256):
        offsets[i] = current_offset
        current_offset += len(char_data[i]) * 2 + 2
    
    with open(output_file, 'w') as f:
        f.write('.table\n')
        f.write('font:\n')
        
        for i in range(256):
            if 32 <= i < 127:
                char_repr = chr(i)
            else:
                char_repr = f'\\{i:02x}'
            
            f.write(f'    .i64 {offsets[i]}  // Character 0x{i:02x} -- `{char_repr}`\n')
        
        f.write('\n')
        
        for i in range(256):
            cmds = char_data[i]
            
            if 32 <= i < 127:
                char_repr = chr(i)
            else:
                char_repr = f'\\{i:02x}'
            
            f.write(f'// Character 0x{i:02x} -- `{char_repr}`\n')
            
            if cmds:
                for cmd, x, y in cmds:
                    encoded = encode_command(cmd, x, y)
                    f.write(f'    .i16 0x{encoded:04x}\n')
            
            f.write(f'    .i16 0x0000\n')
            f.write('\n')
    
    return characters

generated = generate_assembly(IMAGE, OUTPUT)

print("Generated characters:")
for ascii_code in sorted(generated.keys()):
    if 32 <= ascii_code < 127:
        char_repr = chr(ascii_code)
    else:
        char_repr = f'\\x{ascii_code:02x}'
    print(f"  0x{ascii_code:02x} -- `{char_repr}` ({len(generated[ascii_code])} commands)")
